### ISSUE TITLE
Don't remove comments

### ISSUE THREAD

**Issue by vincentducorps** [Jukkales/intellij-propertiessort#1]
Hey,

Thanks for your plugin.

Comments seems to be removed when I use your plugin.
Can you add support to keep them in place ?
Thanks

**Comment by Jukkales** [comment]
Yes, you are right. I will implement this as soon as i have some time :)

**Comment by vincentducorps** [comment]
Up? :)

**Comment by Jukkales** [comment]
Even it is very to late, it is now supported in 0.2 :)
