### ISSUE TITLE
Grouping does not work as intended with key names that contain underscores

### ISSUE THREAD

**Issue by JensPiegsa** [Jukkales/intellij-propertiessort#2]
Grouping properties works fine with key names that contain dots, like:

    group1.key1 = value 1-1
    group1.key2 = value 1-2

    group2.key1 = value 2-1
    group2.key2 = value 2-2

But it does not work with keys that use underscore characters to structure the property tree.
Each key becomes its own group then, e.g.:

    group1_key1 = value 1-1

    group1_key2 = value 1-2

    group2_key1 = value 2-1

    group2_key2 = value 2-2

It would be great, if your plugin can detect underscores as well, or makes it configurable.

**Comment by JensPiegsa** [comment]
#3

**Comment by JensPiegsa** [comment]
see PR #3

**Comment by Jukkales** [comment]
I have rewritten the plugin but took your changes from the PR. Thank you :)
