### ISSUE TITLE
Error after update to 2020.1.2

### ISSUE THREAD

**Issue by Thomas-MB** [Jukkales/intellij-propertiessort#5]
I updated my intelliJ to 2020.1.2 coming from some version of 2019, I think. Now I get an Error-Popup, when trying to sort a properties file (Alt+Ins -> Sort Properties... -> OK): "Error while sorting properties. com/intellij/openapi/actionSystem/DataKeys"

Or another reason could be, that I worked in the meantime in another project where openapi is used. But I don't remember, that I would have installed a plugin for openapi.

**Comment by OSwoboda** [comment]
I have the same issue in 2020.2.1, plugin is not usable like that.
